feat: add new branch and prevent commit to main branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" ]; then
+  echo "⚠️ You can't commit directly to master branch"
+  exit 1
+fi
+
 echo '🏗️👷 Styling, testing and building your project before committing'
 npm run format
 # Check Prettier standards
